# Generated by Django 3.2.10 on 2021-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='gene_id',
            field=models.CharField(max_length=250, verbose_name='基因ID'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='gene_length',
            field=models.CharField(max_length=250, verbose_name='基因长度'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='herb_id',
            field=models.CharField(max_length=250, verbose_name='药物编码'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='tissue_id',
            field=models.CharField(max_length=250, verbose_name='样本组织编码'),
        ),
        migrations.AlterField(
            model_name='cog',
            name='cog_id',
            field=models.CharField(max_length=250, verbose_name='COG ID'),
        ),
        migrations.AlterField(
            model_name='cog',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='cpc',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='cpc',
            name='label',
            field=models.CharField(max_length=250, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='go',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='go',
            name='go_id',
            field=models.CharField(max_length=250, verbose_name='GO ID'),
        ),
        migrations.AlterField(
            model_name='go',
            name='go_ontology',
            field=models.CharField(max_length=250, verbose_name='GO 本体'),
        ),
        migrations.AlterField(
            model_name='go',
            name='go_term',
            field=models.CharField(max_length=250, verbose_name='GO 术语'),
        ),
        migrations.AlterField(
            model_name='kegg',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='kegg',
            name='kegg_id',
            field=models.CharField(max_length=250, verbose_name='KEGG ID'),
        ),
        migrations.AlterField(
            model_name='kog',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='kog',
            name='kog_id',
            field=models.CharField(max_length=250, verbose_name='KOG ID'),
        ),
        migrations.AlterField(
            model_name='nr',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='nr',
            name='nr_id',
            field=models.CharField(max_length=250, verbose_name='NR ID'),
        ),
        migrations.AlterField(
            model_name='pfam',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='pfam',
            name='pfam_id',
            field=models.CharField(max_length=250, verbose_name='Pfam ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barcode_id',
            field=models.CharField(max_length=250, verbose_name='条形码ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='chip_id',
            field=models.CharField(max_length=250, verbose_name='芯片ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_location',
            field=models.CharField(max_length=250, verbose_name='采样地点'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_tissue',
            field=models.CharField(max_length=250, verbose_name='采样组织'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_tissue_detail',
            field=models.CharField(max_length=250, verbose_name='采样组织细节'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collector',
            field=models.CharField(max_length=250, verbose_name='采样人'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='field_store_condition',
            field=models.CharField(max_length=250, verbose_name='野外保存条件'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='field_store_duration',
            field=models.CharField(max_length=250, verbose_name='野外保存时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='herb_id',
            field=models.CharField(max_length=250, verbose_name='药物编码'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='herb_name',
            field=models.CharField(max_length=250, verbose_name='药物名称'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='herb_name_note',
            field=models.CharField(max_length=250, verbose_name='药物名称注释'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lane_id',
            field=models.CharField(max_length=250, verbose_name='Lane ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='receiver',
            field=models.CharField(max_length=250, verbose_name='样本接收人'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_pic_name',
            field=models.CharField(max_length=250, verbose_name='样本照片名称'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='seq_id',
            field=models.CharField(max_length=250, verbose_name='测序编号'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequencing_length_type',
            field=models.CharField(max_length=250, verbose_name='测序长度类型'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequencing_platform',
            field=models.CharField(max_length=250, verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequencing_sample_id',
            field=models.CharField(max_length=250, verbose_name='测序样本ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='temporary_store_condition',
            field=models.CharField(max_length=250, verbose_name='临时保存条件'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tissue_id',
            field=models.CharField(max_length=250, verbose_name='组织编号'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='transport_store_condition',
            field=models.CharField(max_length=250, verbose_name='运输保存条件'),
        ),
        migrations.AlterField(
            model_name='species',
            name='guijing',
            field=models.CharField(max_length=250, verbose_name='药-归经'),
        ),
        migrations.AlterField(
            model_name='species',
            name='herb_name',
            field=models.CharField(max_length=250, verbose_name='药物名称'),
        ),
        migrations.AlterField(
            model_name='species',
            name='herb_pinyin',
            field=models.CharField(max_length=250, verbose_name='药物拼音'),
        ),
        migrations.AlterField(
            model_name='species',
            name='nature',
            field=models.CharField(max_length=250, verbose_name='药-性'),
        ),
        migrations.AlterField(
            model_name='species',
            name='origin',
            field=models.CharField(max_length=250, verbose_name='地源'),
        ),
        migrations.AlterField(
            model_name='species',
            name='palnt_class',
            field=models.CharField(max_length=250, verbose_name='分类纲'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_family',
            field=models.CharField(max_length=250, verbose_name='分类科'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_genus',
            field=models.CharField(max_length=250, verbose_name='分类属'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_name',
            field=models.CharField(max_length=250, verbose_name='植物名称'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_order',
            field=models.CharField(max_length=250, verbose_name='分类目'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_species',
            field=models.CharField(max_length=250, verbose_name='分类种'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_suffix',
            field=models.CharField(max_length=250, verbose_name='种后缀'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taste',
            field=models.CharField(max_length=250, verbose_name='药-味'),
        ),
        migrations.AlterField(
            model_name='species',
            name='tissue',
            field=models.CharField(max_length=250, verbose_name='用药组织'),
        ),
        migrations.AlterField(
            model_name='species',
            name='toxin',
            field=models.CharField(max_length=250, verbose_name='药-毒'),
        ),
        migrations.AlterField(
            model_name='ssr',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='ssr',
            name='ssr_type',
            field=models.CharField(max_length=250, verbose_name='SSR类型'),
        ),
        migrations.AlterField(
            model_name='swissprot',
            name='gene',
            field=models.CharField(max_length=250, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='swissprot',
            name='swissprot_id',
            field=models.CharField(max_length=250, verbose_name='SwissProt ID'),
        ),
    ]
