# Generated by Django 3.2.10 on 2021-12-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211221_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='daodi_or_not',
            field=models.CharField(max_length=10, verbose_name='是否道地药材'),
        ),
        migrations.AlterField(
            model_name='species',
            name='seq_or_not',
            field=models.CharField(max_length=10, verbose_name='是否测序'),
        ),
    ]
