# Generated by Django 3.2.10 on 2021-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20211221_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collection_datetime',
            field=models.CharField(max_length=150, verbose_name='采样时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='receive_datetime',
            field=models.CharField(max_length=150, verbose_name='样本接收时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='transport_datetime',
            field=models.CharField(max_length=150, verbose_name='运输日期'),
        ),
    ]
