# Generated by Django 3.2.10 on 2021-12-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cog',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpc',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='go',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegg',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kog',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nr',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pfam',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssr',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swissprot',
            name='herb_id',
            field=models.CharField(default=200, max_length=250, verbose_name='药物编码'),
            preserve_default=False,
        ),
    ]
