# Generated by Django 3.2.10 on 2021-12-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_go_go_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go',
            name='go_definition',
            field=models.TextField(verbose_name='GO描述'),
        ),
    ]
