# Generated by Django 3.2.10 on 2021-12-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_ssr_ssr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssr',
            name='ssr_pattern',
            field=models.TextField(default='xxx', verbose_name='SSR模式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ssr',
            name='ssr_type',
            field=models.CharField(max_length=50, verbose_name='SSR类型'),
        ),
    ]
